language: python
python:
- "2.7"

install:
- pip install -r requirements.txt

script:
   - export SECRET_KEY='*tq*fbm!vihbcade==1&**lw#zvr7kxz6drfj!n-8ka*1j=9+b'
   - cd dziekanat
   - python manage.py test
